- hosts: webservers
  become: true

  roles:
    - role: datadog.datadog
      become: yes
      tags: monitoring

  tasks:
    - name: Install redmine container
      community.docker.docker_container:
        name: redmine
        image: redmine
        ports:
          - "{{ app_port }}:3000"
        env:
          REDMINE_DB_POSTGRES: "{{ db_host }}"
          REDMINE_DB_PORT: "{{ db_port }}"
          REDMINE_DB_DATABASE: "{{ db_name }}"
          REDMINE_DB_USERNAME: "{{ db_username }}"
          REDMINE_DB_PASSWORD: "{{ db_password }}"
      tags: deploy

    - name: Add cronjob for upmon
      ansible.builtin.cron:
        name: "upmon healthcheck"
        special_time: "daily"
        job: "curl -m 10 --retry 5 {{ upmon_url }}"
      tags: monitoring
